volumes:
  bottlebalance-db:
  bottlebalance-app-uploads:

services:
  bottlebalance-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - bottlebalance-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

  bottlebalance-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - WSGI_MODULE=app:app
      - PYTHONPATH=/opt/app

      - UPLOAD_FOLDER=/opt/app/uploads
      - LOG_FILE=/opt/app/uploads/app.log
      - LOG_LEVEL=INFO

      # --- Existing DB parameters ---
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}

      #Email configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_SSL=${SMTP_SSL}
      - FROM_EMAIL=${FROM_EMAIL}
      - SMTP_TIMEOUT=${SMTP_TIMEOUT}

      # Optional, useful for links in emails (local):
      - APP_BASE_URL=${APP_BASE_URL}
      - SEND_TEST_MAIL=${SEND_TEST_MAIL}

    volumes:
      - bottlebalance-app-uploads:/opt/app/uploads
      
    depends_on:
      bottlebalance-db:
        condition: service_healthy
      #mailhog:
      #  condition: service_started

  #mailhog:
  #  image: mailhog/mailhog
  #  restart: unless-stopped
  #  ports:
  #    - "1025:1025"   # SMTP
  #    - "8025:8025"   # Web UI (http://localhost:8025)
